spring.application.name=infrasub-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/infrasub
spring.datasource.username=infrasub
spring.datasource.password=infrasub_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true